CREATE TABLE TB_USUARIOS (
	ID UUID NOT NULL,
	ENABLED BOOL NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(255) NOT NULL,
	GRUPO_ACESSO_ID UUID NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	TELEFONE VARCHAR(255) NOT NULL,
	CONSTRAINT TB_USUARIOS_PK PRIMARY KEY (ID),
	CONSTRAINT TB_USUARIO_CONSTRAINT_USERNAME_UNIQUE UNIQUE (USERNAME),
	CONSTRAINT TB_USUARIO_TB_GRUPO_ACESSO_FK FOREIGN KEY (GRUPO_ACESSO_ID) REFERENCES TB_GRUPO_ACESSO(ID),
	CONSTRAINT TB_USUARIO_CONSTRAINT_CPFCNPJ_UNIQUE UNIQUE (CPF_CNPJ),
	CONSTRAINT TB_USUARIO_CONSTRAINT_TELEFONE_UNIQUE UNIQUE (TELEFONE)
);


CREATE TABLE TB_INSUMOS(
	ID UUID NOT NULL,
	CODIGO SERIAL4 NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	UNIDADE_MEDIDA INT NOT NULL,
	DESCRICAO VARCHAR(255) NOT NULL,
	ENABLED BOOL NOT NULL,
	CONSTRAINT TB_INSUMOS_PK PRIMARY KEY(ID),
	CONSTRAINT TB_INSUMOS_CONSTRAINT_NOME_UNIQUE UNIQUE (NOME)
);

CREATE TABLE TB_MARCA (
	ID UUID NOT NULL,
	ENABLED BOOL NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CONSTRAINT TB_MARCA_PK PRIMARY KEY (ID),
	CONSTRAINT TB_MARCA_CONSTRAINT_NOME_UNIQUE UNIQUE (NOME)
);


CREATE TABLE TB_FORNECEDORES (
	ID UUID NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	ENABLED BOOL NOT NULL,
	ESTADO VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(255) NOT NULL,
	COMPLEMENTO VARCHAR(255) NOT NULL,
	CONSTRAINT TB_FORNECEDORES_PK PRIMARY KEY (ID),
	CONSTRAINT TB_FORNECEDOR_CONSTRAINT_EMAIL_UNIQUE UNIQUE (EMAIL),
	CONSTRAINT TB_FORNECEDOR_CONSTRAINT_CPFCNPJ_UNIQUE UNIQUE (CPF_CNPJ),
	CONSTRAINT TB_FORNECEDOR_CONSTRAINT_TELEFONE_UNIQUE UNIQUE (TELEFONE)
);


CREATE TABLE TB_CLIENTES (
	ID UUID NOT NULL,
	BAIRRO VARCHAR(255) NOT NULL,
	CEP VARCHAR(255) NOT NULL,
	CIDADE VARCHAR(255) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	ENABLED BOOL NOT NULL,
	ESTADO VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	NUMERO VARCHAR(255) NOT NULL,
	RUA VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(255) NOT NULL,
	COMPLEMENTO VARCHAR(255) NOT NULL,
	CONSTRAINT TB_CLIENTES_PK PRIMARY KEY (ID),
	CONSTRAINT TB_CLIENTE_CONSTRAINT_EMAIL_UNIQUE UNIQUE (EMAIL),
	CONSTRAINT TB_CLIENTE_CONSTRAINT_CPFCNPJ_UNIQUE UNIQUE (CPF_CNPJ),
	CONSTRAINT TB_CLIENTE_CONSTRAINT_TELEFONE_UNIQUE UNIQUE (TELEFONE)
);


CREATE TABLE TB_NOTA_FISCAL (
	ID UUID NOT NULL,
	DATA_COMPRA DATE NOT NULL,
	DATA_INSERCAO DATE NOT NULL,
	NOTA_FISCAL VARCHAR(255) NOT NULL,
	STATUS INT2 NOT NULL,
	USUARIO_INSERCAO_ID UUID NOT NULL,
	FORNECEDOR_ID UUID NOT NULL,
	CONSTRAINT TB_NOTA_FISCAL_PK PRIMARY KEY (ID),
	CONSTRAINT TB_NOTA_FISCAL_TB_USUARIOS_FK FOREIGN KEY (USUARIO_INSERCAO_ID) REFERENCES TB_USUARIOS(ID),
	CONSTRAINT TB_NOTA_FISCAL_TB_FORNECEDORES_FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES TB_FORNECEDORES(ID)
);


CREATE TABLE TB_LANCAMENTO (
	ID UUID NOT NULL,
	DATA_COMPRA DATE NOT NULL,
	DATA_INSERCAO DATE NOT NULL,
	DATA_VENCIMENTO DATE NOT NULL,
	QUANTIDADE FLOAT8 NOT NULL,
	TIPO INT2 NOT NULL,
	VALOR_PAGO FLOAT8 NOT NULL,
	FORNECEDOR_ID UUID NOT NULL,
	INSUMO_ID UUID NOT NULL,
	MARCA_ID UUID NOT NULL,
	NOTA_FISCAL_ID UUID NOT NULL,
	USUARIO_ALTERACAO_ID UUID NULL,
	USUARIO_INSERCAO_ID UUID NOT NULL,
	CONSTRAINT TB_LANCAMENTO_PK PRIMARY KEY (ID),
	CONSTRAINT TB_LANCAMENTO_TB_FORNECEDORES_FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES TB_FORNECEDORES(ID),
	CONSTRAINT TB_LANCAMENTO_TB_NOTA_FISCAL_FK FOREIGN KEY (NOTA_FISCAL_ID) REFERENCES TB_NOTA_FISCAL(ID),
	CONSTRAINT TB_LANCAMENTO_TB_MARCA_FK FOREIGN KEY (MARCA_ID) REFERENCES TB_MARCA(ID),
	CONSTRAINT TB_LANCAMENTO_TB_USUARIOS_FK_1 FOREIGN KEY (USUARIO_ALTERACAO_ID) REFERENCES TB_USUARIOS(ID),
	CONSTRAINT TB_LANCAMENTO_TB_USUARIOS_FK_2 FOREIGN KEY (USUARIO_INSERCAO_ID) REFERENCES TB_USUARIOS(ID),
	CONSTRAINT TB_LANCAMENTO_TB_INSUMOS_FK FOREIGN KEY (INSUMO_ID) REFERENCES TB_INSUMOS(ID)
);
